services:
  - type: web
    name: predict-api
    runtime: python3.9
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free # Specify free tier
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: predict-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: predict-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free # Specify free tier
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://predict-api.onrender.com

databases:
  - name: predict
    databaseName: predict_05qi
    plan: free # Specify free tier