services:
  - type: web
    name: predict-api
    runtime: python3.11
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_application:application --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    plan: free # Specify free tier
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: predict-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHONPATH
        value: .

  - type: web
    name: predict-frontend
    runtime: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free # Specify free tier
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://predict-api.onrender.com

databases:
  - name: predict-db
    databaseName: predict_05qi
    plan: free # Specify free tier