services:
  - type: web
    name: blogpredict-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-postgres-db-name
          property: connectionString
      - key: ENVIRONMENT
        value: production
      # Add other environment variables from your .env file here