services:
  - type: web
    name: predict-api
    runtime: python3.11
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend wsgi:application --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120 --keep-alive 5
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: predict-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: predict-frontend
    runtime: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://predict-api.onrender.com

databases:
  - name: predict-db
    databaseName: predict_05qi
    plan: free